### ISSUE TITLE
Use configuration pushed from ros master

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/head_mcu#1]
Add configuration, e.g. which pins to use as Analog or digital, and in what publishing frequency

**Comment by DarthBubi** [comment]
This is a [starting point](http://wiki.ros.org/rosserial/Overview/Parameters) how to use ROS parameters on an MCU. What do we want to configure besides the obvious ones you mentioned?

**Comment by Cirromulus** [comment]
The Parameters would be usable in [pilsbot/lighting](https://github.com/pilsbot/lighting) for blink cycle duration, party mode changes or not to hardcode the number of LEDs in the strip

**Comment by DarthBubi** [comment]
Yes, but let's discuss the parameters for the lighting MCU in the corresponding repo.

**Comment by Cirromulus** [comment]
ROSSERIAL IS DED
